eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: gateway-service
    appname: gateway-service

spring:
  application:
    name: gateway-service
  profiles:
    active:
      default
  cloud:
    config:
      name: shared
      enabled: true
      uri: http://config-server:8888

server:
  port: 8010
zuul:
  prefix: /api
  routes:
    vacation-service:
      path: /vacation-service/**
      serviceId: vacation-service
      url: http://localhost:8082/
  sensitive-headers:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
