eureka:
  client:
    service-url:
      #defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
      defaultZone: http://${REGISTRY_HOST}:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: vacation-service

spring:
  application:
    name: vacation-service
  profiles:
    active:
      default
  cloud:
    config:
      name: shared
      enabled: true
      uri: http://${config.host:localhost}:${config.port:8888}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://IP_HERE:3306/employee?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: USERNAME_HERE
    password: PASSWORD_HERE
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    #hibernate:
      #ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    virtual-host: ${RabbitMqVirtualHost}
    host: ${RabbitMqHost}
    port: ${RabbitMqPort}
    username: ${RabbitMqUsername}
    password: ${RabbitMqPassword}
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000

logging:
  level:
    org: ERROR

server:
  port: 8020

