eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: vacation-service

spring:
  application:
    name: vacation-service
  profiles:
    active:
      default
  cloud:
    config:
      name: shared
      enabled: true
      uri: http://config-server:8888
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://IP_HERE:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
    username: USERNAME_HERE
    password: PASSWORD_HERE
    #initialization-mode: always
    #data: classpath:data.sql
    #continue-on-error: false
    #schema: classpath:schema.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  rabbitmq:
    virtual-host: ${RabbitMqVirtualHost}
    host: ${RabbitMqHost}
    port: ${RabbitMqPort}
    username: ${RabbitMqUsername}
    password: ${RabbitMqPassword}
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000


logging:
  level:
    org: ERROR

server:
  port: 8020

