eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
  instance:
    hostname: config-server-dev
  #ip-address: localhost
    #prefer-ip-address: true


server:
  port: 8887

spring:
  cloud:
    config:
      server:
        git:
          uri: http://93.189.103.52:85/khalid/configuration-repository.git
          clone-on-start: true
  application:
    name: config-server
  profiles:
    active: dev
