eureka:
  client:
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: config-server
  #ip-address: localhost
    #prefer-ip-address: true


server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: http://93.189.103.52:85/khalid/configuration-repository.git
  application:
    name: config-server
